### ISSUE TITLE
String compare - Timing information

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/pico#47]
# Research story

As a researcher I would like to know how long it (usually) takes to run `a == b` in python, c, java and ruby (for different string sizes and string similarities/differences).
# Tasks
- [ ] Create python2.7 and python3k, c, java and ruby programs to compare two strings
- [ ] Use [this code](https://security.stackexchange.com/questions/50900/are-there-any-working-proof-of-concept-string-comparison-timing-attacks) for C tests
- [ ] Use [this code](https://security.stackexchange.com/questions/50900/are-there-any-working-proof-of-concept-string-comparison-timing-attacks) for Java
- [ ] Read source for [python3 strcmp](https://hg.python.org/cpython/file/c4a86fe52006/Objects/unicodeobject.c#l10633) and link from wiki
- [ ] Commit all sources to a `pico-string-compare-local` repo
- [ ] Create graphs for x) string length y) time it took to compare string where strings are in Ax, Ay shape and A length increases
- [ ] Test with different strings for each language:
  - [ ] `A` vs. `A`
  - [ ] `A` vs. `B`
  - [ ] `A` \* 128 vs. `A` \* 128
  - [ ] `A` \* 32 vs. `A` \* 32
  - [ ] `A` \* 127 + `B` vs. `A` \* 127 + `C`
  - [ ] `A` \* 31 + `B` vs. `A` \* 31 + `C`
  - [ ] `A` \* 64 + `B` + `A` \* 64 vs. `A` \* 64 + `C` + `A` \* 64
- [ ] Use the best profiler for each language to measure 1M string compares and then divide to get how much it takes to compare one
- [ ] Write results to wiki
  - [ ] Include python/java/ruby versions
  - [ ] Include OS information (kernel, etc.)
  - [ ] Include CPU info (64bit)
- [ ] Compare results with previous research
# References
- [Min measurable delay](https://youtu.be/9i9jhPo9jTM?t=2073) vs. [time it actually takes to compare strings](https://youtu.be/9i9jhPo9jTM?t=2493)
- [time trial talk also discusses this issue](https://youtu.be/md6NEmq1n-A?t=1825)
- Also [here](https://youtu.be/md6NEmq1n-A?t=2041) a table with the time it takes to compare 1 byte in different programming languages.
